{
 "title": "Proposal GrafanaBoard",
 "description": "Proposal GrafanaBoard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "category",
    "query": "SHOW TAG VALUES WITH KEY = \"category\""
   },
   {
    "name": "group",
    "label": "group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\" WHERE \"category\" =~ /$category/"
   },
   {
    "name": "page",
    "query": "SHOW TAG VALUES WITH KEY = \"page\" WHERE \"group\" =~ /$group/ AND \"category\" =~ /$category/"
   },
   {
    "name": "browser",
    "query": "SHOW TAG VALUES WITH KEY = \"browser\" WHERE \"group\" =~ /$group/ AND \"page\"  =~ /$page/ AND \"category\" =~ /$category/"
   },
   {
    "name": "connectivity",
    "query": "SHOW TAG VALUES WITH KEY = \"connectivity\" WHERE \"group\" =~ /$group/ AND \"page\"  =~ /$page/ AND \"browser\" =~ /$browser/ AND \"category\" =~ /$category/"
   },
   { "name": "query0" },
   { "name": "query1" }
  ]
 },
 "panels": [
  { "title": "Sustainability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CO2 based on estimated daily views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "measurement": "totalCO2",
     "select": [
      [
       { "params": [ "p90" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2 per Page View",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "p90" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "Total CO2 based on estimated daily views",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "totalCO2",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "sustainable" }
     ]
    }
   ]
  },
  {
   "title": "CO2 per Page View",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "co2PerPageView",
     "query": "SELECT last(\"value\") FROM \"co2PerPageView\" WHERE (\"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"page\" =~ /^$page$/ AND \"category\" =~ /^$category$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"origin\" = 'sustainable') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "sustainable" }
     ]
    }
   ]
  },
  {
   "title": "CO2 First Party",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "co2FirstParty",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "sustainable" }
     ]
    }
   ]
  },
  {
   "title": "CO2 Third Party",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "co2ThirdParty",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" }
     ]
    }
   ]
  },
  {
   "title": "Content Sizes First Party",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CSS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "query": "SELECT mean(\"value\") FROM \"default\".\"contentSize\" WHERE (\"category\" =~ /^$category$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"contentType\" = 'css' AND \"party\" = 'thirdParty') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    },
    {
     "alias": "Fonts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "query": "SELECT mean(\"value\") FROM \"default\".\"contentSize\" WHERE (\"category\" =~ /^$category$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"contentType\" = 'font' AND \"party\" = 'thirdParty') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "font" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    },
    {
     "alias": "HTML",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "html" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    },
    {
     "alias": "Java Script ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    },
    {
     "alias": "Images",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "image" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    }
   ]
  },
  {
   "title": "Content Sizes Third Party",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CSS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    },
    {
     "alias": "Fonts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "font" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    },
    {
     "alias": "HTML",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "html" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    },
    {
     "alias": "Java Script ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    },
    {
     "alias": "Images",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "image" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    }
   ]
  },
  {
   "title": "JavaScript Content Sizes First Party",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Java Script",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" }
     ]
    }
   ]
  },
  {
   "title": "JavaScript Content Sizes Third Party",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Java Script",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" },
      { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
     ]
    }
   ]
  },
  {
   "title": "CO2 per URL (Table last)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "page::tag" ], "type": "tag" }
     ],
     "measurement": "co2PerPageView",
     "query": "SELECT last(\"p90\") FROM \"autogen\".\"co2PerPageView\" WHERE (\"page\" =~ /.*/) AND $timeFilter GROUP BY \"page\"::tag ORDER BY time DESC",
     "select": [
      [
       { "params": [ "p90" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "CO2 Usage per URL as Time series",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "alias": "360° Panoramabilder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_360-grad-panoramabilder_" }
     ]
    },
    {
     "alias": "Anreise",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_anreise_" }
     ]
    },
    {
     "alias": "Bestuhlungspläne",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_bestuhlungsplaene_" }
     ]
    },
    {
     "alias": "Datenschutzerklärung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_datenschutzerklaerung_" }
     ]
    },
    {
     "alias": "Gastronomie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_gastronomie_" }
     ]
    },
    {
     "alias": "Impressum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_impressum_" }
     ]
    },
    {
     "alias": "Kontakt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_kontakt_" }
     ]
    },
    {
     "alias": "Preisliste",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_preisliste_" }
     ]
    },
    {
     "alias": "Raumangebot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_raumangebot_" }
     ]
    },
    {
     "alias": "Theater Preise",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_theater-preise_" }
     ]
    },
    {
     "alias": "Theater",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_theater_" }
     ]
    },
    {
     "alias": "Veranstaltungen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_veranstaltungen_" }
     ]
    },
    {
     "alias": "Startseite",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2PerPageView",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "_" }
     ]
    }
   ]
  }
 ]
}